package com.Levels;

import java.util.ArrayList;

public final class LevelOne extends Level {
	public LevelOne() {
		locked = false;
		tiles = new ArrayList<>();
		backgroundTiles = new ArrayList<>();
		tiles.add(".....................................................");
		tiles.add(".....................................................");
		tiles.add(".....................................................");
		tiles.add(".....................................................");
		tiles.add(".....................................................");
		tiles.add(".....................................................");
		tiles.add(".....................................................");
		tiles.add(".....................................................");
		tiles.add(".............................h.......................");
		tiles.add(".....................................................");
		tiles.add(".....................................................");
		tiles.add("............................300000>..................");
		tiles.add(".................h..........qssssfk..................");
		tiles.add("............................:;...qi<.................");
		tiles.add(".................p.8a.....a.:;....qf<................");
		tiles.add("3000000000000000000000>..30000>....lk................");
		tiles.add("ffffffffiffffffffffffiovvnffffr....lf<...............");
		tiles.add("fifffffffffffffffffffffffffifk....elfo10000000000000>");
		tiles.add("ffffffffffiffffffffifffffffffk..tvvnfsssiffffffffffff");
		tiles.add("fffffffffffffffffffffffffffffk..qsssr...qfffiffffffff");
		tiles.add("ffffffffffffffifffffffffiffffk...........qffffffffiff");
		tiles.add("fffffifffffffffffffffffffffffke.........7.lffffifffff");
		tiles.add("ffffffffffffiffffffffiffffffitvu..8.zzze..lfiffffffff");
		tiles.add("ffffffffffffffffffffffffffffffftvvvvywxvvvnffffffffff");
		tiles.add("fffffffffffffffffifffffffffffffffffffffffffffffffffff");
		tiles.add("ffffffffffffffffffffffiffffffffffffifffffffffffffffff");
		tiles.add("ffffffffiffffffffffffffffffffffffffffffffffffffffffff");
		tiles.add("fffffffffffffffffffffffffffffifffffffffffffffffffffff");
		tiles.add("fffffffffffffffffffffffffffffffffffffffffffffffffffff");
		tiles.add(".....................................................");
		tiles.add(".....................................................");
		tiles.add(".....................................................");
		tiles.add(".....................................................");
		backgroundTiles.add("m....................................................");
		backgroundTiles.add(".....................................................");
		backgroundTiles.add(".....................................................");
		backgroundTiles.add(".....................................................");
		backgroundTiles.add(".....................................................");
		backgroundTiles.add(".....................................................");
		backgroundTiles.add(".....................................................");
		backgroundTiles.add(".....................................................");
		backgroundTiles.add("...............................g.....................");
		backgroundTiles.add(".....................................................");
		backgroundTiles.add(".....................................................");
		backgroundTiles.add(".....................................................");
		backgroundTiles.add("...................g.....g..:f5555...................");
		backgroundTiles.add(".............................555555..................");
		backgroundTiles.add("..........................b..555655..................");
		backgroundTiles.add(".............................5555555.................");
		backgroundTiles.add(".............................5545565f................");
		backgroundTiles.add(".............................5555555f................");
		backgroundTiles.add(".............................555565555555............");
		backgroundTiles.add(".............................555555555555............");
		backgroundTiles.add(".............................54555555565555..........");
		backgroundTiles.add(".............................55555545555555..........");
		backgroundTiles.add(".............................ff555555555555..........");
		backgroundTiles.add("...............................ffffffffff............");
		backgroundTiles.add(".....................................................");
		backgroundTiles.add(".....................................................");
		backgroundTiles.add(".....................................................");
		backgroundTiles.add(".....................................................");
		backgroundTiles.add(".....................................................");
		backgroundTiles.add(".....................................................");
		backgroundTiles.add(".....................................................");
		backgroundTiles.add(".....................................................");
		backgroundTiles.add(".....................................................");
	}
}
